name: Sync luci-theme-design

on:
  workflow_run:
    workflows: ["Delete workflows"]
    types:
      - completed

jobs:
  sync-theme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set timezone to China Standard Time
        run: sudo timedatectl set-timezone Asia/Shanghai

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: luci-theme-design

      - name: Sync upstream luci-theme-design
        run: |
          cd luci-theme-design
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' ! -name 'README.md' -exec rm -rf {} +
          git clone -b openwrt-23.05 --single-branch --filter=blob:none https://github.com/coolsnowwolf/luci.git upstream
          LATEST_COMMIT=$(cd upstream && git log -1 --pretty=format:"%s" themes/luci-theme-design)
          LATEST_COMMIT_TIME=$(cd upstream && git log -1 --pretty=format:"%cI" themes/luci-theme-design)
          LATEST_COMMIT_AUTHOR=$(cd upstream && git log -1 --pretty="%an <%ae>" themes/luci-theme-design)
          echo "LATEST_COMMIT=${LATEST_COMMIT}" >> $GITHUB_ENV
          echo "LATEST_COMMIT_TIME=${LATEST_COMMIT_TIME}" >> $GITHUB_ENV
          echo "LATEST_COMMIT_AUTHOR=${LATEST_COMMIT_AUTHOR}" >> $GITHUB_ENV
          cp -r upstream/themes/luci-theme-design/* ./
          rm -rf upstream

      - name: Commit and Force Push changes
        if: success()
        run: |
          cd luci-theme-design
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${{env.LATEST_COMMIT}}" --author="${{env.LATEST_COMMIT_AUTHOR}}" --date="${{env.LATEST_COMMIT_TIME}}"
          git push
